### ISSUE TITLE
can not find the head file

### ISSUE THREAD

**Issue by wyycv** [lifunudt/CORB-SLAM#1]
I am not very familiar with ros, when I run catkin_make, there is an error:
/home/catkin_ws/src/corbslam_client/include/Cache.h:20:45: fatal error: corbslam_server/corbslam_insert.h: No such file or directory
 #include "corbslam_server/corbslam_insert.h"

Do you have any idea with my problem?

**Comment by SYSUHPK** [comment]
Hello, I met the same problem, how do you solve it?
